### ISSUE TITLE
RuntimeBlockStateRegistry::isRegistered() not exist. CustomiesBlockFactory at line 87

### ISSUE THREAD

**Issue by markeev** [DavyCraft648/Customies-NG#2]
The Customies-NG-pm5 plugin is encountering a critical error with the following message: "Call to undefined method pocketmine\block\RuntimeBlockStateRegistry::isRegistered()" at line 87 of the CustomiesBlockFactory.

**Comment by Azvyl** [comment]
Fixed by 977c65126c706b47fa1daf33b0dce0da7c301e3b
