### ISSUE TITLE
Closures with non-thread-safe $this cannot be made thread-safe

### ISSUE THREAD

**Issue by markeev** [DavyCraft648/Customies-NG#3]
The Customise-Plugin is encountering a critical error with the following message: "Closures with non-thread-safe $this cannot be made thread-safe" at line 27 of the AsyncRegisterBlocksTask. 

Stack trace:

 #0 plugins/Customies-NG-pm5/src/block/CustomiesBlockFactory(54): customiesdevs\customies\task\AsyncRegisterBlocksTask->__construct(array[1])
  #1 pmsrc/src/scheduler/AsyncPool(104): customiesdevs\customies\block\CustomiesBlockFactory::customiesdevs\customies\block\{closure}(int 0)
  #2 plugins/Customies-NG-pm5/src/block/CustomiesBlockFactory(55): pocketmine\scheduler\AsyncPool->addWorkerStartHook(object Closure#302713)
  #3 plugins/Customies-NG-pm5/src/Customies(18): customiesdevs\customies\block\CustomiesBlockFactory->addWorkerInitHook()
  #4 pmsrc/src/scheduler/ClosureTask(57): customiesdevs\customies\Customies::customiesdevs\customies\{closure}()
  #5 pmsrc/src/scheduler/TaskHandler(113): pocketmine\scheduler\ClosureTask->onRun()
  #6 pmsrc/src/scheduler/TaskScheduler(137): pocketmine\scheduler\TaskHandler->run()
  #7 pmsrc/src/plugin/PluginManager(530): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(int 1)
  #8 pmsrc/src/Server(1777): pocketmine\plugin\PluginManager->tickSchedulers(int 1)
  #9 pmsrc/src/Server(1666): pocketmine\Server->tick()
  #10 pmsrc/src/Server(1066): pocketmine\Server->tickProcessor()
  #11 pmsrc/src/PocketMine(339): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#5, string[41] /Users/markmojseev/Documents/servers/pm5/, string[49] /Users/markmojseev/Documents/servers/pm5/plugins/)
  #12 pmsrc/src/PocketMine(362): pocketmine\server()

**Comment by ArasakaID** [comment]
the item registrar closure must be static

**Comment by Azvyl** [comment]
What php version are you using?

**Comment by Azvyl** [comment]
there is a change in pthreads 5.3.0 for PM5 https://github.com/pmmp/pthreads/commit/403894bba8774f131df8bd8cd3dfce20617028d6

the error is caused by your plugin, to fix it you can change your closure to static or downgrade your php version to 8.1.16/8.2.3
