### ISSUE TITLE
 ReflectionException - Property pocketmine\network\mcpe\convert\BlockStateDictionary::$stateDataToStateIdLookupCache does not exist

### ISSUE THREAD

**Issue by markeev** [DavyCraft648/Customies-NG#4]
### Description
When running the server with the Customies-NG-pm5 plugin, a ReflectionException occurs, causing the server to crash. The error message states that the property pocketmine\network\mcpe\convert\BlockStateDictionary::$stateDataToStateIdLookupCache does not exist.

### Steps to Reproduce
Set up a server with the NG-PM and Customies-NG-pm5 plugin and add a custom Block.
Start the server.
Observe the server crashing with a ReflectionException.

### Expected Behavior
The server should start without any issues, and the Customies-NG-pm5 plugin should function properly.

### Actual Behavior
The server crashes with a ReflectionException related to the pocketmine\network\mcpe\convert\BlockStateDictionary::$stateDataToStateIdLookupCache property.

### StackTrace

-    plugins/Customies-NG-pm5/src/block/BlockPalette(47): ReflectionProperty->__construct(object pocketmine\network\mcpe\convert\BlockStateDictionary#141371, string[29] stateDataToStateIdLookupCache)
-    pmsrc/src/utils/SingletonTrait(31): customiesdevs\customies\block\BlockPalette->__construct()
-    pmsrc/src/utils/SingletonTrait(36): customiesdevs\customies\block\BlockPalette::make()
-    plugins/Customies-NG-pm5/src/block/CustomiesBlockFactory(156): customiesdevs\customies\block\BlockPalette::getInstance()
-    plugins/UniqueItems/src/radovinetch/block/CustomBlock(22): customiesdevs\customies\block\CustomiesBlockFactory->registerBlock(_object Closure#57278, string[24] servername:block_exemple, object customiesdevs\customies\block\Model#57273, object customiesdevs\customies\item\CreativeInventoryInfo#57276_)

**Comment by Azvyl** [comment]
Thanks, I forgot to commit the changes I made to fix this
I'll push it while I'm on my laptop

**Comment by markeev** [comment]
Please try to run with PM-NG. I am getting a lot of errors.

**Comment by Azvyl** [comment]
Can you send it? I don't get any error

**Comment by markeev** [comment]
The errors disappeared when I installed the older PHP binaries as you wrote.
