### ISSUE TITLE
Undefined class 'ThreadSafeArray' 

### ISSUE THREAD

**Issue by markeev** [DavyCraft648/Customies-NG#7]
I have to choose between PM-NG and Customies-NG. It doesn't make sense!

* pthreads not work with new version of [PM-NG](https://github.com/DavyCraft648/PM-NG)

[ERROR] Selected PHP binary does not satisfy some requirements.
 Unable to find the pmmpthread (pmmpthread) extension.

* pmmpthread not work with [Customies-NG](https://github.com/DavyCraft648/Customies-NG)

pmmp\thread\NonThreadSafeValueError: "Closures with non-thread-safe $this cannot be made thread-safe" (EXCEPTION) in "plugins/Customies-NG-pm5/src/task/AsyncRegisterBlocksTask" at line 31

**Comment by Azvyl** [comment]
you need pmmpthread for both to work

> `Closures with non-thread-safe $this cannot be made thread-safe`

like I said in the previous issue, it's caused by your plugin. #3
